#!/usr/bin/env python3
"""MiSTer MRA for the gunbird2m set, and the set's zip (the last step of tools/build.py --set gunbird2m).

The MRA follows the core's own 'Gunbird 2 (set 1).mra' (MiSTer-devel/Arcade-PsikyoSH2_MiSTer, core PsikyoSH2) with
the gunbird2m files and CRCs from out/roms/gunbird2m.crc.json.  ROM layout the core loads (PsikyoSH2.sv, PS5):
gfx 0x0000000-0x3BFFFFF, sound 0x3C00000-0x3FFFFFF, program 0x4800000, data 0x4A00000, EEPROM 0x4C00000.  gunbird2m's
bank-3 pair (3l.u6 / 3h.u13) is 2 x 8 MB, but the core's gfx space ends at 0x3C00000 (the sound ROM follows), so only
the first 6 MB of each is loaded (bank 3 = 12 MB); the tool checks that nothing past that is used (the port's gfx
ends well below).  The hiscore block (rom index 3) and the other settings are the stock set's.
Writes mra/_alternatives/_Gunbird 2/<MAME description>.mra (git-tracked) and out/roms/gunbird2m.zip (the files of
out/roms/gunbird2m).
usage: make_mra.py"""
import os, sys, json, zipfile
ROOT = os.path.abspath(os.path.dirname(__file__) + '/..')
SET = 'gunbird2m'
DESCRIPTION = 'Gunbird 2 Makai (Morrigan Backport)'      # the MAME description (tools/mame/gunbird2m_driver.patch)
MAMEVERSION = '0289'                                   # the MAME the set's driver entry is maintained for
MRA_DIR = 'mra/_alternatives/_Gunbird 2'               # beside the core's 'Gunbird 2 (set 2)' alternative
BANK3_LOAD = 0x600000                                  # bytes of each bank-3 chip the core can hold

TEMPLATE = '''<misterromdescription>
	<!-- generated by tools/make_mra.py from out/roms/{set}.crc.json - do not edit -->
	<rbf>PsikyoSH2</rbf>
	<setname>{set}</setname>
	<mameversion>{mamever}</mameversion>
	<description>{desc}</description>
	<rotation>Vertical (CCW)</rotation>
	<year>1998</year>
	<manufacturer>Psikyo (hack)</manufacturer>
	<buttons names="Button 1,Button 2,Button 3,Start,Coin,Test,Service" />

	<switches default="41">
		<dip bits="0,1,2,3" name="Region" ids="Japan,International Ver A,International Ver B"/>
		<dip bits="6" name="Debug" ids="On,Off"/>
	</switches>

	<rom index="0" md5="" zip="{set}.zip" address="0x30000000">
		<interleave output="64">
			<part crc="{0l.u3}" name="0l.u3" map="125600" />
			<part crc="{0h.u10}" name="0h.u10" map="1256" />
		</interleave>
		<interleave output="64">
			<part crc="{1l.u4}" name="1l.u4" map="125600" />
			<part crc="{1h.u11}" name="1h.u11" map="1256" />
		</interleave>
		<interleave output="64">
			<part crc="{2l.u5}" name="2l.u5" map="125600" />
			<part crc="{2h.u12}" name="2h.u12" map="1256" />
		</interleave>
		<!-- bank 3: 2 x 64M EPROMs; the core's gfx space ends at 0x3C00000, the first {b3} bytes of each are used -->
		<interleave output="64">
			<part crc="{3l.u6}" name="3l.u6" map="125600" length="{b3}" />
			<part crc="{3h.u13}" name="3h.u13" map="1256" length="{b3}" />
		</interleave>
		<interleave output="64">
			<part crc="{sound.u9}" name="sound.u9" map="12345678" />
		</interleave>

		<part repeat="0x800000">00</part>
		<interleave output="64">
			<part crc="{2_prog_l.u16}" name="2_prog_l.u16" map="2165" />
			<part crc="{1_prog_h.u17}" name="1_prog_h.u17" map="216500" />
		</interleave>
		<part repeat="0x100000">00</part>
		<interleave output="64">
			<part crc="{3_pdata.u1}" name="3_pdata.u1" map="21436587" />
		</interleave>
		<part repeat="0x180000">00</part>
		<interleave output="64">
			<part crc="{eeprom-gunbird2.bin}" name="eeprom-gunbird2.bin" map="21436587" />
		</interleave>
	</rom>
	<rom index="2" md5="" >
		<part>21</part>
	</rom>

	<rom index="3" md5="none">
		<part>
			00 04 C7 58 00 28 00 70
			00 04 C7 80 00 3C 1E 00
		</part>
	</rom>
	<nvram index="4" size="356" />
</misterromdescription>
'''


def main():
    d = f'{ROOT}/out/roms/{SET}'
    crcs = json.load(open(f'{ROOT}/out/roms/{SET}.crc.json'))
    for n in ('3l.u6', '3h.u13'):                      # what the core cannot hold must be empty
        tail = open(f'{d}/{n}', 'rb').read()[BANK3_LOAD:]
        if any(tail): sys.exit(f'{n}: data past {BANK3_LOAD:#x} - beyond the MiSTer core\'s gfx space (0x3C00000)')
    fields = {n: c for n, (c, _, _) in crcs.items()}
    fields.update({'set': SET, 'mamever': MAMEVERSION, 'desc': DESCRIPTION, 'b3': f'0x{BANK3_LOAD:X}'})
    mra = TEMPLATE
    for n, c in fields.items(): mra = mra.replace('{' + n + '}', c)
    missing = [l for l in mra.splitlines() if 'crc="{' in l]
    if missing: sys.exit('no CRC for: ' + ' '.join(missing))
    os.makedirs(ROOT + '/' + MRA_DIR, exist_ok=True)
    out = f'{ROOT}/{MRA_DIR}/{DESCRIPTION}.mra'
    open(out, 'w').write(mra)
    # the set's zip, fixed timestamps so an unchanged set gives an identical file
    zpath = f'{ROOT}/out/roms/{SET}.zip'
    with zipfile.ZipFile(zpath + '.tmp', 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for n in sorted(crcs):
            zi = zipfile.ZipInfo(n, date_time=(1998, 1, 1, 0, 0, 0)); zi.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(zi, open(f'{d}/{n}', 'rb').read())
    os.replace(zpath + '.tmp', zpath)
    print(f'wrote {out}\nwrote {zpath}')


if __name__ == '__main__':
    main()
