#!/usr/bin/env python3
"""Generate Morrigan graphics artefacts:
   out/gfx/place.json   gfx-ROM placements {offset: file}
   src/gen_gfx.c        palette data (const, program ROM)
Palette mode 'high': pixel indices start at 16 and sprites use colr 0xFF, so pen p maps to palette entry
0xFF0 + p (>= 0x1000): lines 0x100-0x13F exist in palette RAM (0x5000 bytes) but are never written by the game."""
import os, sys, json
ROOT = os.path.dirname(os.path.abspath(__file__)) + '/..'
sys.path.insert(0, ROOT + '/tools')
import gfxconv
cfg = json.load(open(ROOT + '/src/morrigan_layout.json'))['gfx']
FS = ROOT + '/assets/dc/US/fs/'
os.makedirs(ROOT + '/out/gfx', exist_ok=True)
sheets = [('jiki6', 'JIKI6.CHR', cfg['tnum_base'] * 256, 'pal_morrigan_game')]
place, cdefs = {}, ['/* generated by tools/make_gfx.py - do not edit */', '#include "arcade.h"', '']
for name, f, off, pal_name in sheets:
    cells = gfxconv.load_cells(FS + f)
    pal = gfxconv.build_palette([cells], start=cfg['index_start'], max_colours=0xBF)   # pens 0xC0+ may carry alpha
    tiles = gfxconv.cells_to_tiles(cells, pal)
    open(ROOT + f'/out/gfx/{name}.tiles', 'wb').write(tiles)
    place[f'{off:08x}'] = f'{name}.tiles'
    first, last = min(pal.values()), max(pal.values())
    cols = [0] * (last - first + 1)
    for c555, i in pal.items(): cols[i - first] = gfxconv.rgb888(c555)
    cdefs.append(f'const u32 {pal_name}[{len(cols)}] = {{' + ', '.join(f'0x{v:08X}' for v in cols) + '};')
    cdefs.append(f'const u16 {pal_name}_first = 0x{cfg["colr"] * 16 + first:X};   /* palette entry of the first colour */')
    cdefs.append(f'const u16 {pal_name}_count = {len(cols)};')
    print(f'{name}: {len(cells)} tiles @ gfx {off:#x} (tnum {off // 256:#x}), {len(pal)} colours -> entries '
          f'{cfg["colr"] * 16 + first:#x}-{cfg["colr"] * 16 + last:#x}')
json.dump(place, open(ROOT + '/out/gfx/place.json', 'w'), indent=0)
open(ROOT + '/src/gen_gfx.c', 'w').write('\n'.join(cdefs) + '\n')
