#!/usr/bin/env python3
"""Generate Morrigan's stage-demo scenes for the arcade (src/gen_story.c / .h, section .story).

Inputs: out/stagedemo/scenes.json (tools/stagedemo_extract.py), src/story/stagedemo_text.json (EN transcribed from
the US DC images, JP arcade font codes matched from the JP DC images).

Arcade mechanics used (see re/NOTES.md "Story screens"):
  - G_StageDemo picks (*(hdr+8))[0][stage-1][slot]; the slot comes from src/story.c gb2_demo_slot (DC 7-character
    triangle {0,7,13,18,22,25,26}), so the stage tables are rebuilt with 27 slots: the 21 original scenes move to
    their DC slots, Morrigan's six scenes fill slots 26 (solo, also Aine+Morrigan), 6, 12, 17, 21, 24.
  - scene script = start sub of the stage (sets w11 = stage-1, palettes, window) ; w12 = message set ;
    SetNewAct message window ; per event: portrait (w0F char, w0E face, w0A = charNo it stands for, side logic at
    0x0C13EA) or message (w13 index, w0C frames; loop at 0x0C1388 with w15 = w0B = 0 and w10 = message table) ;
    w14 = 1 ; Wait 20 ; StageEnd ; Sleep.
  - message table: Fnc57 reads *(w10 + w11*0x54 + w12*4) -> 6 pointers {JP m0,m1,m2, EN m0,m1,m2}; w12 = 21..26
    as on the DC, w10 = gb2_demo_msgtbl - 21*4.
  - portraits: Fnc56 row tables (0x0BC3FC side 0 / 0x0BC418 side 1) replaced by 9-character tables:
    7 = Morrigan (bank 0xA0), 8 = Morrigan (bank 0xB0, used in the scene with portrait character 0 whose bank is
    0xA0).  Her palette is loaded into the bank by the scene (PltBlockSet).  DC face 4 falls back to face 0 as on
    the DC (its portrait routine only distinguishes faces 1-3).
"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gbres import Space, ROOT

A = Space('arcade')
T6 = [0, 6, 11, 15, 18, 20]                      # arcade triangle (6 characters, 21 slots)
T7 = [0, 7, 13, 18, 22, 25, 26]                  # DC triangle (7 characters, 27 slots)
M_SLOTS = {26: 21, 6: 22, 12: 23, 17: 24, 21: 25, 24: 26}   # DC slot -> w12 of Morrigan's scene
START = [0x0C10D4, 0x0C1130, 0x0C118C, 0x0C11E8, 0x0C1240, 0x0C1274]
WINDOW, PORTRAIT_SIDE, MSG_LOOP = 0x0C1A78, 0x0C13EA, 0x0C1388
HDR8 = A.u32(A.u32(0x0608002C) + 8)             # 0x60228: (*(hdr+8))[0] = stage list
STAGE_LIST = A.u32(HDR8)


def slot_map():
    """arcade slot -> DC slot for every pair of characters 1..6"""
    m = {}
    for a in range(1, 7):
        for b in range(a, 7):
            m[T6[a - 1] + b - a] = T7[a - 1] + b - a
    return m


class Script:
    """seq script as u32 words (two script words each); pointer operands must be 4-byte aligned, so a Nop word
    (0x0000, skipped by the VM) is inserted before an instruction whose pointer would be misaligned"""
    def __init__(self): self.w = []                     # items: int word, or ('p', expr) = 2 words

    def _align_ptr(self, words_before_ptr):
        if (len(self.words()) + words_before_ptr) % 2: self.w.append(0)

    def words(self):
        n = []
        for x in self.w: n += [x] if isinstance(x, int) else [x, x]
        return n

    def call(self, target): self._align_ptr(1); self.w += [0x0005, ('p', target)]
    def setnewact(self, target): self._align_ptr(2); self.w += [0x0020, 0x0200, ('p', target)]
    def pltblockset(self, line, table): self._align_ptr(2); self.w += [0x00A1, line, ('p', table)]
    def setw(self, reg, val):
        if isinstance(val, int): self.w += [0x000B, 0x0840, reg, (val >> 16) & 0xFFFF, val & 0xFFFF]
        else: self._align_ptr(3); self.w += [0x000B, 0x0840, reg, ('p', val)]
    def raw(self, *ws): self.w += list(ws)

    def c_init(self):
        out, cur = [], []
        for x in self.w:
            if isinstance(x, int): cur.append(x)
            else:
                assert len(cur) % 2 == 0; out += [f'0x{cur[i]:04X}{cur[i + 1]:04X}' for i in range(0, len(cur), 2)]
                cur = []; out.append(f'(u32)({x[1]})' if not isinstance(x[1], int) else f'0x{x[1]:08X}')
        if len(cur) % 2: cur.append(0)
        out += [f'0x{cur[i]:04X}{cur[i + 1]:04X}' for i in range(0, len(cur), 2)]
        return out


def ptr(x): return x if isinstance(x, str) else f'0x{x:08X}'


def main():
    scenes = json.load(open(ROOT + '/out/stagedemo/scenes.json'))
    text = json.load(open(ROOT + '/src/story/stagedemo_text.json'))
    c = ['/* generated by tools/port_stagedemo.py - do not edit */', '#include "arcade.h"', '#include "gen_gfx.h"',
         '#include "gen_story.h"', '#define STORY __attribute__((section(".story"), aligned(4)))', '']
    h = ['/* generated by tools/port_stagedemo.py - do not edit */', '#ifndef GEN_STORY_H', '#define GEN_STORY_H',
         'extern const void *const gb2_demo_stages[7];', 'extern const void *const gb2_demo_portraits_s0[9 * 8];',
         'extern const void *const gb2_demo_portraits_s1[9 * 8];', '#endif']
    # ---- text ---------------------------------------------------------------------------------------------
    for key, s in text['en'].items():
        b = s.encode('ascii').replace(b'\n', b'\xfe') + b'\xff'
        c.append(f'static const u8 en_{key}[{len(b)}] STORY = {{' + ','.join(f'0x{x:02X}' for x in b) + '};')
    for key, codes in text['jp'].items():
        c.append(f'static const u16 jp_{key}[{len(codes)}] STORY = {{' + ','.join(f'0x{x:04X}' for x in codes) + '};')
    # ---- message sets (6 pointers) + table ----------------------------------------------------------------
    mt = {}
    for sc in scenes:
        n = len([e for e in sc['events'] if 'msg' in e])
        keys = [f"s{sc['stage']}_w{sc['w12']}_m{min(m, n - 1)}" for m in range(3)]
        name = f"ms_s{sc['stage']}_w{sc['w12']}"
        c.append(f'static const void *const {name}[6] STORY = {{' +
                 ', '.join([f'jp_{k}' for k in keys] + [f'en_{k}' for k in keys]) + '};')
        mt[(sc['stage'] - 1) * 21 + sc['w12'] - 21] = name
    c.append('const void *const gb2_demo_msgtbl[6 * 21] STORY = {' +
             ', '.join(mt.get(i, '0') for i in range(6 * 21)) + '};')
    # ---- scene scripts ------------------------------------------------------------------------------------
    for sc in scenes:
        s = Script(); st = sc['stage']
        with0 = any('port' in e and e['port'][0] == 0 for e in sc['events'])
        mchar, bank = (8, 0xB0) if with0 else (7, 0xA0)
        s.call(START[st - 1])
        s.pltblockset(bank, 'pal_demo_lines')                  # Morrigan's portrait palette into the free bank
        s.setw(0x12, sc['w12'])
        s.setnewact(WINDOW)
        for e in sc['events']:
            if 'port' in e:
                ch, face = e['port']
                if ch == 6: arc, face = mchar, (face if face <= 3 else 0)
                else: arc = ch
                s.setw(0x0F, arc); s.setw(0x0E, face); s.setw(0x0A, ch + 1)
                s.call(PORTRAIT_SIDE)
            else:
                s.setw(0x13, e['msg']); s.setw(0x0C, e['dur'])
                s.setw(0x15, 0); s.setw(0x0B, 0); s.setw(0x10, 'gb2_demo_msgtbl - 21')
                s.call(MSG_LOOP)
        s.setw(0x14, 1); s.raw(0xFFEC, 0x0036, 0x0002)          # Wait 20, StageEnd, Sleep
        ini = s.c_init()
        c.append(f'static const u32 scene_s{st}_w{sc["w12"]}[{len(ini)}] STORY = {{' + ', '.join(ini) + '};')
    # ---- stage tables (27 slots) + list -------------------------------------------------------------------
    sm = slot_map()
    tbls = []
    for st in range(7):
        old = A.u32(STAGE_LIST + 4 * st)
        slots = ['0'] * 27
        for arc, dc in sm.items(): slots[dc] = ptr(A.u32(old + 4 * arc))
        for dc, w12 in M_SLOTS.items():
            slots[dc] = f'scene_s{st + 1}_w{w12}' if st < 6 else ptr(A.u32(old))
        name = f'stage_tbl{st + 1}'
        c.append(f'static const void *const {name}[27] STORY = {{' + ', '.join(f'(const void *){x}' for x in slots) + '};')
        tbls.append(name)
    c.append('const void *const gb2_demo_stages[7] STORY = {' + ', '.join(tbls) + '};')
    # ---- portrait row tables (9 characters x 8 faces per side) --------------------------------------------
    for side, base in ((0, A.u32(0xBC3FC)), (1, A.u32(0xBC418))):
        rows = [f'(const void *)0x{A.u32(base + 4 * i):08X}' for i in range(7 * 8)]
        for bank in ('a0', 'b0'):
            rows += [f'obj_demo_s{side}f{f if f < 4 else 0}_{bank}' for f in range(8)]
        c.append(f'const void *const gb2_demo_portraits_s{side}[9 * 8] STORY = {{' + ', '.join(rows) + '};')
    open(ROOT + '/src/gen_story.c', 'w').write('\n'.join(c) + '\n')
    open(ROOT + '/src/gen_story.h', 'w').write('\n'.join(h) + '\n')
    print('stage list at', hex(HDR8), '->', hex(STAGE_LIST), '; scenes', len(scenes))


if __name__ == '__main__':
    main()
