#!/usr/bin/env python3
"""High-score ranking: Morrigan's animated sprite for a new entry (src/gen_ranking.c, section .story).

The ranking script (story table +0x1C, arcade 0x0AC394 / DC 0x8C3E4D88) starts a task per new entry with w1 =
character (charNo - 1); a JumpCompare chain picks the character's AnimObj loop.  The arcade chain ends at w1 == 5
(0x0AC4AC -> 0x0AC718); the DC adds w1 == 6 (0x8C3E51DC).  The arcade's last JumpCompare is retargeted
(src/patches.txt, sym32 0x0AC4B6) to gb2_rank_chain here: w1 == 5 -> the original Aine loop, w1 == 6 -> Morrigan's
loop (palette bank 0x90 loaded with PltBlockSet, then the DC frame order), else End as the original fall-through.
Graphics: tools/make_gfx.py group 'ranking' (RANKING.CHR frames 0x8C389910 + 5 x 6)."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from port_stagedemo import Script
from gbres import ROOT

AINE_LOOP = 0x000AC718
DC_ORDER = [2, 1, 0, 1, 2, 3, 4, 3]            # DC 0x8C3E51DC: 99a0, 9958, 9910, 9958, 99a0, 99e8, 9a30, 99e8
BANK = 0x90


def main():
    s = Script()
    def jcmp(value, target): s._align_ptr(5); s.w += [0x000A, 0x0140, 0x0001, value >> 16, value & 0xFFFF, ('p', target)]
    def byte_off(): return 2 * len(s.words())
    jcmp(5, f'0x{AINE_LOOP:08X}')
    s._align_ptr(5); s.w += [0x000A, 0x0140, 0x0001, 0, 6]; morrigan_ref = len(s.w); s.w.append(None)
    s.raw(0x0001)                                                  # End (original fall-through)
    s.pltblockset(BANK, 'pal_ranking_lines')
    loop = byte_off()
    s.w[morrigan_ref] = ('p', f'(const u8 *)gb2_rank_chain + MORRIGAN_OFF')
    for k in DC_ORDER:
        s._align_ptr(1); s.w += [0x0061, ('p', f'obj_rank_m{k}_{BANK:02x}'), 6, 4, 0]
        s.raw(0xFFE0)                                              # Wait 32
    s._align_ptr(1); s.w += [0x0008, ('p', f'(const u8 *)gb2_rank_chain + {loop}')]
    # the Morrigan entry point is the PltBlockSet (before the loop): find its byte offset
    off = 0
    for i, x in enumerate(s.w):
        if x == 0x00A1: break
        off += 2 if isinstance(x, int) else 4
    ini = [v.replace('MORRIGAN_OFF', str(off)) for v in s.c_init()]
    c = ['/* generated by tools/port_ranking.py - do not edit */', '#include "arcade.h"', '#include "gen_gfx.h"',
         '#define STORY __attribute__((section(".story"), aligned(4)))', '',
         'extern const u32 gb2_rank_chain[];',
         f'const u32 gb2_rank_chain[{len(ini)}] STORY = {{' + ', '.join(ini) + '};']
    open(ROOT + '/src/gen_ranking.c', 'w').write('\n'.join(c) + '\n')
    print(f'ranking chain: {len(ini)} words, Morrigan entry +{off:#x}, loop +{loop:#x}')


if __name__ == '__main__':
    main()
