#!/usr/bin/env python3
"""Morrigan's story text (stage demos and endings, English + Japanese) read back from the Dreamcast images, so no
transcribed text has to be kept in the repository.

Writes (git-ignored, read by port_stagedemo.py / port_endings.py):
  out/stagedemo/stagedemo_text.json  {"en": {scene key: "line\\nline"}, "jp": {scene key: [arcade font codes]}}
  out/stagedemo/ending_text.json     {"en": {US text composite: [lines]}, "jp": {US text composite: [lines]}}

How: every glyph in the DC text images is always the same exact bitmap, so a line is split into glyphs and each glyph
is looked up by a hash of its pixels in re/story_glyphs.json ({table: {hash: character}} - no text, no pixels).
  en_demo  US stage-demo messages (out/stagedemo/img/<key>_US.png from stagedemo_extract.py): 16-pixel line cells,
           glyphs = runs of non-empty columns, a gap of >= space_px[0] pixels = round(gap / space_px[1]) spaces
  en_end   US ending text composites (END*.CHR): each part column is one line of 16x16 cells (shown rotated 90 degrees
           counter-clockwise), lines ordered by display position as tools/jpend.py; glyphs / spaces as en_demo
  jp_end   JP ending text composites: one glyph per 16x16 cell, an empty cell inside a line = ' ' (leading ones
           are indentation and dropped)
  jp_demo  the stage-demo Japanese is out/stagedemo/jp_codes.json (tools/jptranscribe.py, exact arcade-font match)
A few spots where the transcription is a context choice between identical bitmaps (e.g. 〜 / ー) or differs from the
image are kept as character edits in the same file ("fix": [[table, key, line, position, old, new], ...]), and one
choice box whose lines are listed question-first although its geometry is not, as a line order ("order").

usage: story_text.py            generate (and fail on unknown glyphs)
       story_text.py --learn    rebuild re/story_glyphs.json from existing transcriptions (src/story/*.json or --from
                                <dir>), then check that generating reproduces them exactly"""
import os, sys, json, hashlib, difflib
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dcend, seqdis
ROOT = os.path.abspath(os.path.dirname(__file__) + '/..')
SD = ROOT + '/out/stagedemo'
TABLE = ROOT + '/re/story_glyphs.json'
NOTE_DEMO = ('Morrigan stage-demo text (generated by tools/story_text.py). en: read from the US DC v1.000 message '
             'images; jp: arcade font codes matched glyph-for-glyph from the JP DC v1.002 images (tools/jptranscribe.py)')
NOTE_END = ('Morrigan ending texts per DC text composite (US address; generated by tools/story_text.py). en: read '
            'from the US DC END*.CHR images; jp: read from the JP DC v1.002 images (encoded with tools/jpcodes.py at '
            'port time). Line positions come from the DC composite geometry.')


def ghash(m):
    return hashlib.sha1(np.packbits(m).tobytes() + bytes(m.shape)).hexdigest()[:16]


def runs(cols):
    out, x = [], 0
    while x < len(cols):
        if cols[x]:
            x0 = x
            while x < len(cols) and cols[x]: x += 1
            out.append((x0, x))
        else: x += 1
    return out


# ---- line images -> glyph sequences ([(hash, gap before)] per line) ------------------------------------------------
def glyphs_of_line(m):
    """m: 16-row bool line image; returns [(hash, gap in pixels before the glyph or None)]"""
    out, prev = [], None
    for x0, x1 in runs(m.any(0)):
        out.append((ghash(m[:, x0:x1]), None if prev is None else x0 - prev)); prev = x1
    return out


def demo_lines(key):
    im = np.asarray(Image.open(f'{SD}/img/{key}_US.png').convert('RGB')); m = im.sum(-1) > 150
    return [glyphs_of_line(m[16 * i:16 * i + 16]) for i in range(m.shape[0] // 16) if m[16 * i:16 * i + 16].any()]


def composite_columns(reg, fn, addr, img):
    """[(top, left, [16x16 bool cell or None, ...])] per displayed line, ordered as displayed"""
    cs = dcend.cells(reg, fn)
    lines = []
    for p in dcend.parts(img, addr):
        for c in range(p['W']):
            g = []
            for i in range(p['H']):
                k = p['idx'] + i * p['W'] + c
                m = (cs[k] & 0x8000) != 0 if k < len(cs) else np.zeros((16, 16), bool)
                g.append(m if m.sum() >= 3 else None)
            while g and g[-1] is None: g.pop()
            if g: lines.append((-(p['x'] + (c + 1) * 16), p['y'], g))
    lines.sort(key=lambda l: (l[0], l[1]))
    return lines


def end_en_lines(key, fn, img):
    out = []
    for top, left, g in composite_columns('US', fn, int(key, 16), img):
        row = np.concatenate([np.rot90(c if c is not None else np.zeros((16, 16), bool), 1) for c in g], 1)
        out.append(glyphs_of_line(row))
    return out


def end_jp_lines(addr, fn, img):
    """line images (16 rows, text orientation); leading empty cells are indentation (the arcade places lines from
    the composite geometry) and are dropped"""
    out = []
    for _, _, g in composite_columns('JP', fn, addr, img):
        while g and g[0] is None: g = g[1:]
        out.append(np.concatenate([np.rot90(c if c is not None else np.zeros((16, 16), bool), 1) for c in g], 1))
    return out


def crop_hash(c):
    ys, xs = np.nonzero(c)
    return ghash(c[ys.min():ys.max() + 1, xs.min():xs.max() + 1])


def jp_cells(row, off=0, pitch=16):
    """glyph hashes (glyph cropped to its bounding box) of a JP line image cut into cells of `pitch` pixels from
    x = off (None = empty cell), trimmed"""
    r = np.pad(row, ((0, 0), (0, 16)))
    g = []
    for x in range(off, row.shape[1], pitch):
        c = r[:, x:x + pitch]
        g.append(crop_hash(c) if c.sum() >= 3 else None)
    while g and g[0] is None: g = g[1:]
    while g and g[-1] is None: g.pop()
    return g


# ---- decode ---------------------------------------------------------------------------------------------------------
def spaces(gap, sp):
    """sp = [smallest gap that is a space, typical space gap]"""
    return 0 if gap is None or gap < sp[0] else max(1, round(gap / sp[1]))


def look(table, h, where, unknown):
    if h in table: return table[h]
    if unknown is None: raise KeyError(f'unknown glyph {h} in {where}')
    return unknown.setdefault(h, chr(0xE000 + len(unknown)))      # learn mode: private-use placeholder


def decode_latin(lines, table, sp, where, unknown=None):
    out = []
    for n, line in enumerate(lines):
        s = ''
        for h, gap in line:
            s += ' ' * spaces(gap, sp) + look(table, h, f'{where} line {n}', unknown)
        out.append(s)
    return out


def jp_segments(row, table):
    """proportionally spaced JP line: glyphs = unions of consecutive non-empty column runs (<= 16 px wide), chosen so
    that as many as possible are known glyphs (dynamic programming over the runs)"""
    rs = runs(row.any(0)); n = len(rs)
    best = [(0, [])] + [None] * n
    for i in range(1, n + 1):
        for j in range(i - 1, -1, -1):
            if rs[i - 1][1] - rs[j][0] > 16: break
            if best[j] is None: continue
            h = crop_hash(row[:, rs[j][0]:rs[i - 1][1]])
            sc = best[j][0] + (1 if h in table else -1)
            if best[i] is None or sc > best[i][0]: best[i] = (sc, best[j][1] + [h])
    return best[n][1]


def decode_jp(lines, table, where, unknown=None):
    """a line whose glyphs are not on the 16-pixel cell grid (one DC text is drawn proportionally spaced) is
    segmented by jp_segments"""
    out = []
    for n, row in enumerate(lines):
        line = jp_cells(row)
        if any(h is not None and h not in table for h in line):
            line = jp_segments(row, table)
        s = ''
        for h in line:
            if h is None: s += ' '; continue
            s += look(table, h, f'{where} line {n}', unknown)
        out.append(s)
    return out


def apply_fixes(res, fixes):
    """fix = [table, key, line, pos, old, new]: replace old (may be '') by new at pos of that line"""
    for t, key, n, pos, old, new in sorted(fixes, key=lambda f: -f[3]):
        lines = res[t][key]
        s = lines[n]
        assert s[pos:pos + len(old)] == old, (t, key, n, pos, old, s)
        lines[n] = s[:pos] + new + s[pos + len(old):]


def sources():
    owner = json.load(open(ROOT + '/re/end_text_owner.json'))
    pairs = json.load(open(ROOT + '/re/end_text_pairs.json'))
    keys_demo = list(json.load(open(SD + '/jp_codes.json')))
    US, JP = seqdis.Image('dc_US'), seqdis.Image('dc_JP')
    raw = {'en_demo': {k: demo_lines(k) for k in keys_demo},
           'en_end': {k: end_en_lines(k, owner[k], US) for k in owner},
           'jp_end': {k: end_jp_lines(int(pairs[k], 16), owner[k], JP) for k in owner}}
    return raw, keys_demo, list(owner)


def generate(raw, T):
    res = {'en_demo': {}, 'en_end': {}, 'jp_end': {}}
    for k, lines in raw['en_demo'].items(): res['en_demo'][k] = decode_latin(lines, T['en_demo'], T['space_px']['en_demo'], k)
    for k, lines in raw['en_end'].items(): res['en_end'][k] = decode_latin(lines, T['en_end'], T['space_px']['en_end'], k)
    for k, lines in raw['jp_end'].items(): res['jp_end'][k] = decode_jp(lines, T['jp_end'], k)
    for tk, order in T.get('order', {}).items():              # line order where the composite geometry differs
        t, k = tk.split(':'); res[t][k] = [res[t][k][i] for i in order]
    apply_fixes(res, T.get('fix', []))
    return res


def write(res, keys_demo, keys_end):
    jp = json.load(open(SD + '/jp_codes.json'))
    demo = {'_note': NOTE_DEMO, 'en': {k: '\n'.join(res['en_demo'][k]) for k in keys_demo}, 'jp': {k: jp[k] for k in keys_demo}}
    end = {'_note': NOTE_END, 'en': {k: res['en_end'][k] for k in keys_end}, 'jp': {k: res['jp_end'][k] for k in keys_end}}
    json.dump(demo, open(SD + '/stagedemo_text.json', 'w'), ensure_ascii=False, indent=1)
    json.dump(end, open(SD + '/ending_text.json', 'w'), ensure_ascii=False, indent=1)
    return demo, end


def learn(src):
    raw, keys_demo, keys_end = sources()
    demo = json.load(open(src + '/stagedemo_text.json')); end = json.load(open(src + '/ending_text.json'))
    want = {'en_demo': {k: demo['en'][k].split('\n') for k in keys_demo}, 'en_end': end['en'], 'jp_end': end['jp']}
    T = {'_note': 'glyph-pixel hash -> character for tools/story_text.py (no text, no pixels); order = displayed line '
                  'order where it is not the geometric one; fix = character edits [table, key, line, position, old, new] '
                  'where the transcription is not the image\'s literal reading',
         'en_demo': {}, 'en_end': {}, 'jp_end': {}, 'space_px': {}, 'fix': []}
    # glyph tables: align glyphs with the non-space characters of lines whose counts agree
    for t in ('en_demo', 'en_end', 'jp_end'):
        votes, gaps_sp, gaps_no = {}, [], []
        for k, lines in raw[t].items():
            for line, s in zip(lines, want[t][k]):
                if t == 'jp_end':
                    hs = [h for h in jp_cells(line) if h is not None]; chars = [c for c in s if c != ' ']
                else:
                    hs = [h for h, _ in line]; chars = [c for c in s if c != ' ']
                if len(hs) != len(chars): continue
                if t != 'jp_end':
                    j = 0
                    for i, c in enumerate(s):
                        if c == ' ': continue
                        if j: (gaps_sp if s[i - 1] == ' ' else gaps_no).append(line[j][1])
                        j += 1
                for h, c in zip(hs, chars): votes.setdefault(h, {}).setdefault(c, 0); votes[h][c] += 1
        T[t] = {h: max(v, key=v.get) for h, v in sorted(votes.items())}
        if t != 'jp_end':
            T['space_px'][t] = [min(gaps_sp), max(set(gaps_sp), key=gaps_sp.count)]
            assert max(gaps_no) < min(gaps_sp), (t, max(gaps_no), min(gaps_sp))
    # glyphs seen only in lines whose glyph count differs from the transcription: align and learn 1:1 matches
    for t in ('en_demo', 'en_end', 'jp_end'):
        unknown = {}
        for k, lines in raw[t].items():
            dec = decode_jp(lines, T[t], k, unknown) if t == 'jp_end' else \
                decode_latin(lines, T[t], T['space_px'][t], k, unknown)
            back = {v: h for h, v in unknown.items()}
            for g, w in zip(dec, want[t][k]):
                for op, a1, a2, b1, b2 in difflib.SequenceMatcher(None, g, w, autojunk=False).get_opcodes():
                    if op == 'replace' and a2 - a1 == b2 - b1:
                        for x, y in zip(g[a1:a2], w[b1:b2]):
                            if x in back and y != ' ': T[t][back[x]] = y
        still = [h for h in unknown if h not in T[t]]
        assert not still, (t, still)
    # line order where the displayed order is not the geometric one (lines are a permutation), then character edits
    T['order'] = {}
    got = generate(raw, T)
    for t in ('en_demo', 'en_end', 'jp_end'):
        for k in want[t]:
            g, w = got[t][k], want[t][k]
            if g != w and sorted(g) == sorted(w) and len(set(g)) == len(g):
                T['order'][f'{t}:{k}'] = [g.index(x) for x in w]
    got = generate(raw, T)
    for t in ('en_demo', 'en_end', 'jp_end'):
        for k in want[t]:
            for n, (g, w) in enumerate(zip(got[t][k], want[t][k])):
                for op, a1, a2, b1, b2 in difflib.SequenceMatcher(None, g, w, autojunk=False).get_opcodes():
                    if op != 'equal': T['fix'].append([t, k, n, a1, g[a1:a2], w[b1:b2]])
    json.dump(T, open(TABLE, 'w'), ensure_ascii=False, indent=0)
    print(f'{TABLE}: ' + ', '.join(f'{t} {len(T[t])} glyphs' for t in ('en_demo', 'en_end', 'jp_end')) +
          f', space {T["space_px"]}, {len(T["order"])} line orders, {len(T["fix"])} character edits')
    for f in T['fix']: print('  edit', f)
    return want


def main():
    if '--learn' in sys.argv:
        src = sys.argv[sys.argv.index('--from') + 1] if '--from' in sys.argv else ROOT + '/src/story'
        learn(src)
        demo_want = json.load(open(src + '/stagedemo_text.json')); end_want = json.load(open(src + '/ending_text.json'))
    T = json.load(open(TABLE))
    raw, keys_demo, keys_end = sources()
    demo, end = write(generate(raw, T), keys_demo, keys_end)
    print(f'wrote {SD}/stagedemo_text.json ({len(demo["en"])} scenes), {SD}/ending_text.json ({len(end["en"])} texts)')
    if '--learn' in sys.argv:
        ok = demo['en'] == demo_want['en'] and demo['jp'] == demo_want['jp'] and end['en'] == end_want['en'] and \
            end['jp'] == end_want['jp']
        print('reproduces the transcriptions exactly' if ok else 'MISMATCH with the transcriptions')
        sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
